<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Pre-fetch all category IDs by name for clean lookups
        $cats = Category::pluck('id', 'name');

        $products = [
            // ── Computer & Laptop (6 products) ──────────────────────────────
            [
                'category_id'    => $cats['Computer & Laptop'],
                'name'           => 'Laptop ASUS Vivobook 14 M1405',
                'sku'            => 'CLT-001',
                'description'    => 'Laptop tipis AMD Ryzen 5, 16GB RAM, 512GB SSD, layar 14" Full HD.',
                'purchase_price' => 7_500_000,
                'selling_price'  => 8_999_000,
                'stock'          => 25,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Computer & Laptop'],
                'name'           => 'Laptop Lenovo LOQ 15APH9',
                'sku'            => 'CLT-002',
                'description'    => 'Laptop gaming Ryzen 7, RTX 4060, 16GB RAM, 512GB SSD, 144Hz.',
                'purchase_price' => 13_000_000,
                'selling_price'  => 15_499_000,
                'stock'          => 12,
                'minimum_stock'  => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Computer & Laptop'],
                'name'           => 'Laptop Acer Swift Go 14',
                'sku'            => 'CLT-003',
                'description'    => 'Laptop ultrabook Intel Core Ultra 5, 16GB LPDDR5, 512GB SSD.',
                'purchase_price' => 9_200_000,
                'selling_price'  => 10_999_000,
                'stock'          => 18,
                'minimum_stock'  => 4,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Computer & Laptop'],
                'name'           => 'Mini PC Beelink EQ12',
                'sku'            => 'CLT-004',
                'description'    => 'Mini PC Intel N100, 16GB RAM, 500GB SSD, konsumsi daya rendah.',
                'purchase_price' => 2_100_000,
                'selling_price'  => 2_599_000,
                'stock'          => 30,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Computer & Laptop'],
                'name'           => 'Laptop HP 14 Core i5',
                'sku'            => 'CLT-005',
                'description'    => 'Laptop mainstream Intel Core i5, 8GB RAM, 256GB SSD.',
                'purchase_price' => 6_200_000,
                'selling_price'  => 7_299_000,
                'stock'          => 20,
                'minimum_stock'  => 4,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Computer & Laptop'],
                'name'           => 'Laptop Dell Inspiron 15 3000',
                'sku'            => 'CLT-006',
                'description'    => 'Laptop bisnis Intel Core i3, 8GB RAM, 256GB SSD, layar anti-glare.',
                'purchase_price' => 5_500_000,
                'selling_price'  => 6_499_000,
                'stock'          => 8,
                'minimum_stock'  => 2,
                'status'         => 'inactive',
            ],

            // ── Smartphone (6 products) ──────────────────────────────────────
            [
                'category_id'    => $cats['Smartphone'],
                'name'           => 'Samsung Galaxy A55 5G',
                'sku'            => 'SMP-001',
                'description'    => 'Smartphone 5G Exynos 1480, kamera 50MP, baterai 5000mAh, IP67.',
                'purchase_price' => 4_800_000,
                'selling_price'  => 5_699_000,
                'stock'          => 40,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Smartphone'],
                'name'           => 'Xiaomi Redmi Note 13 Pro',
                'sku'            => 'SMP-002',
                'description'    => 'Smartphone 5G Snapdragon 7s, layar AMOLED 200MP, fast charge 67W.',
                'purchase_price' => 3_100_000,
                'selling_price'  => 3_799_000,
                'stock'          => 55,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Smartphone'],
                'name'           => 'Realme C65',
                'sku'            => 'SMP-003',
                'description'    => 'HP terjangkau MediaTek Helio G85, 8GB RAM, 256GB, baterai 5000mAh.',
                'purchase_price' => 1_600_000,
                'selling_price'  => 1_999_000,
                'stock'          => 70,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Smartphone'],
                'name'           => 'OPPO A78 5G',
                'sku'            => 'SMP-004',
                'description'    => 'Smartphone 5G Snapdragon 695, fast charge 33W, kamera 50MP.',
                'purchase_price' => 2_500_000,
                'selling_price'  => 2_999_000,
                'stock'          => 45,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Smartphone'],
                'name'           => 'iPhone 15 128GB',
                'sku'            => 'SMP-005',
                'description'    => 'iPhone terbaru chip A16 Bionic, Dynamic Island, USB-C, kamera 48MP.',
                'purchase_price' => 12_500_000,
                'selling_price'  => 14_999_000,
                'stock'          => 15,
                'minimum_stock'  => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Smartphone'],
                'name'           => 'Samsung Galaxy S24 FE',
                'sku'            => 'SMP-006',
                'description'    => 'Flagship terjangkau Exynos 2500, kamera 50MP, layar AMOLED 120Hz.',
                'purchase_price' => 7_800_000,
                'selling_price'  => 9_299_000,
                'stock'          => 22,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],

            // ── Gaming (5 products) ──────────────────────────────────────────
            [
                'category_id'    => $cats['Gaming'],
                'name'           => 'Logitech G102 LIGHTSYNC',
                'sku'            => 'GMG-001',
                'description'    => 'Mouse gaming kabel RGB, 6 tombol programable, sensor 8000 DPI.',
                'purchase_price' => 185_000,
                'selling_price'  => 249_000,
                'stock'          => 80,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Gaming'],
                'name'           => 'Rexus Daxa M84R',
                'sku'            => 'GMG-002',
                'description'    => 'Keyboard mekanikal TKL, RGB per-key, switch red, anti-ghosting.',
                'purchase_price' => 380_000,
                'selling_price'  => 499_000,
                'stock'          => 35,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Gaming'],
                'name'           => 'Headset Rexus Thundervox HX8',
                'sku'            => 'GMG-003',
                'description'    => 'Headset gaming 7.1 surround, mikrofon noise-cancelling, RGB, USB.',
                'purchase_price' => 250_000,
                'selling_price'  => 329_000,
                'stock'          => 50,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Gaming'],
                'name'           => 'Controller DualSense PS5',
                'sku'            => 'GMG-004',
                'description'    => 'Kontroler orisinal PlayStation 5, haptic feedback, adaptive triggers.',
                'purchase_price' => 750_000,
                'selling_price'  => 899_000,
                'stock'          => 20,
                'minimum_stock'  => 4,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Gaming'],
                'name'           => 'Gaming Chair Rexus GC-X01',
                'sku'            => 'GMG-005',
                'description'    => 'Kursi gaming ergonomis, bantal lumbar, sandaran kaki, material PU.',
                'purchase_price' => 1_800_000,
                'selling_price'  => 2_299_000,
                'stock'          => 10,
                'minimum_stock'  => 2,
                'status'         => 'inactive',
            ],

            // ── Storage (5 products) ─────────────────────────────────────────
            [
                'category_id'    => $cats['Storage'],
                'name'           => 'Kingston A400 SSD 240GB',
                'sku'            => 'STG-001',
                'description'    => 'SSD SATA 2.5" 240GB, baca 500MB/s, tulis 350MB/s.',
                'purchase_price' => 260_000,
                'selling_price'  => 329_000,
                'stock'          => 60,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Storage'],
                'name'           => 'Samsung 870 EVO SSD 500GB',
                'sku'            => 'STG-002',
                'description'    => 'SSD SATA 2.5" 500GB, baca 560MB/s, tulis 530MB/s, V-NAND.',
                'purchase_price' => 620_000,
                'selling_price'  => 749_000,
                'stock'          => 45,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Storage'],
                'name'           => 'WD Green NVMe SSD 256GB',
                'sku'            => 'STG-003',
                'description'    => 'SSD M.2 NVMe PCIe Gen3, baca 2400MB/s, efisien daya.',
                'purchase_price' => 300_000,
                'selling_price'  => 389_000,
                'stock'          => 55,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Storage'],
                'name'           => 'SanDisk Ultra USB 3.0 Flashdisk 64GB',
                'sku'            => 'STG-004',
                'description'    => 'USB Flashdisk 64GB, kecepatan baca 130MB/s, USB 3.0.',
                'purchase_price' => 110_000,
                'selling_price'  => 149_000,
                'stock'          => 120,
                'minimum_stock'  => 15,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Storage'],
                'name'           => 'Seagate Barracuda HDD 1TB',
                'sku'            => 'STG-005',
                'description'    => 'Hard disk internal 3.5" SATA 1TB, 7200 RPM, cache 256MB.',
                'purchase_price' => 550_000,
                'selling_price'  => 679_000,
                'stock'          => 30,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],

            // ── Networking (5 products) ──────────────────────────────────────
            [
                'category_id'    => $cats['Networking'],
                'name'           => 'TP-Link Archer C6 AC1200',
                'sku'            => 'NET-001',
                'description'    => 'Router WiFi dual-band AC1200, 4 antena, MU-MIMO, Gigabit LAN.',
                'purchase_price' => 310_000,
                'selling_price'  => 399_000,
                'stock'          => 40,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Networking'],
                'name'           => 'TP-Link TL-SG105 Switch 5 Port',
                'sku'            => 'NET-002',
                'description'    => 'Switch Gigabit unmanaged 5 port, plug and play, tanpa konfigurasi.',
                'purchase_price' => 130_000,
                'selling_price'  => 169_000,
                'stock'          => 65,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Networking'],
                'name'           => 'TP-Link EAP225 Access Point',
                'sku'            => 'NET-003',
                'description'    => 'Access point ceiling-mount dual-band AC1350, PoE, Omada Cloud.',
                'purchase_price' => 550_000,
                'selling_price'  => 699_000,
                'stock'          => 25,
                'minimum_stock'  => 4,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Networking'],
                'name'           => 'Kabel LAN Cat6 20m',
                'sku'            => 'NET-004',
                'description'    => 'Kabel LAN UTP Cat6 panjang 20 meter, sudah dipasang konektor RJ45.',
                'purchase_price' => 65_000,
                'selling_price'  => 89_000,
                'stock'          => 100,
                'minimum_stock'  => 15,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Networking'],
                'name'           => 'Modem Router ZTE MF283+',
                'sku'            => 'NET-005',
                'description'    => 'Modem router 4G LTE, WiFi 300Mbps, dukungan kartu SIM all-operator.',
                'purchase_price' => 380_000,
                'selling_price'  => 479_000,
                'stock'          => 20,
                'minimum_stock'  => 4,
                'status'         => 'active',
            ],

            // ── Accessories (5 products) ─────────────────────────────────────
            [
                'category_id'    => $cats['Accessories'],
                'name'           => 'Charger GaN 65W USB-C',
                'sku'            => 'ACC-001',
                'description'    => 'Charger GaN 65W tiga port (2x USB-C + 1x USB-A), kompatibel laptop & HP.',
                'purchase_price' => 160_000,
                'selling_price'  => 219_000,
                'stock'          => 90,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Accessories'],
                'name'           => 'Kabel USB-C to USB-C 100W 1m',
                'sku'            => 'ACC-002',
                'description'    => 'Kabel USB-C braided 100W PD fast charge, transfer data 480Mbps.',
                'purchase_price' => 55_000,
                'selling_price'  => 79_000,
                'stock'          => 150,
                'minimum_stock'  => 20,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Accessories'],
                'name'           => 'USB Hub 4 Port 3.0 Orico',
                'sku'            => 'ACC-003',
                'description'    => 'USB Hub 4 port USB 3.0, kecepatan transfer 5Gbps, desain kompak.',
                'purchase_price' => 90_000,
                'selling_price'  => 119_000,
                'stock'          => 80,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Accessories'],
                'name'           => 'Pelindung Layar Anti-Gores Tempered Glass',
                'sku'            => 'ACC-004',
                'description'    => 'Tempered glass 9H untuk smartphone ukuran 6.1"–6.7", full cover.',
                'purchase_price' => 18_000,
                'selling_price'  => 29_000,
                'stock'          => 200,
                'minimum_stock'  => 30,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Accessories'],
                'name'           => 'Stand Laptop Adjustable Aluminium',
                'sku'            => 'ACC-005',
                'description'    => 'Stand laptop aluminium, sudut 0–45°, kompatibel laptop 10"–17".',
                'purchase_price' => 75_000,
                'selling_price'  => 99_000,
                'stock'          => 60,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],

            // ── Electronics (5 products) ─────────────────────────────────────
            [
                'category_id'    => $cats['Electronics'],
                'name'           => 'Smart TV Samsung 43" 4K',
                'sku'            => 'ELC-001',
                'description'    => 'Smart TV 43 inci UHD 4K, Tizen OS, HDR, WiFi, Bluetooth.',
                'purchase_price' => 4_200_000,
                'selling_price'  => 4_999_000,
                'stock'          => 15,
                'minimum_stock'  => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Electronics'],
                'name'           => 'Speaker Bluetooth JBL Flip 6',
                'sku'            => 'ELC-002',
                'description'    => 'Speaker portable Bluetooth 5.1, tahan air IP67, baterai 12 jam.',
                'purchase_price' => 1_050_000,
                'selling_price'  => 1_299_000,
                'stock'          => 30,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Electronics'],
                'name'           => 'Earphone TWS Xiaomi Redmi Buds 5',
                'sku'            => 'ELC-003',
                'description'    => 'TWS earphone ANC 46dB, baterai total 40 jam, Bluetooth 5.3.',
                'purchase_price' => 280_000,
                'selling_price'  => 349_000,
                'stock'          => 70,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Electronics'],
                'name'           => 'Kipas Angin Meja USB Rechargeable',
                'sku'            => 'ELC-004',
                'description'    => 'Kipas meja 3 kecepatan, baterai 4000mAh, portabel, senyap.',
                'purchase_price' => 75_000,
                'selling_price'  => 99_000,
                'stock'          => 100,
                'minimum_stock'  => 15,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Electronics'],
                'name'           => 'Power Bank Anker 20000mAh',
                'sku'            => 'ELC-005',
                'description'    => 'Power bank 20000mAh, fast charge 22.5W, dua port output, LED.',
                'purchase_price' => 350_000,
                'selling_price'  => 449_000,
                'stock'          => 50,
                'minimum_stock'  => 8,
                'status'         => 'active',
            ],

            // ── Office Supplies (5 products) ─────────────────────────────────
            [
                'category_id'    => $cats['Office Supplies'],
                'name'           => 'Mouse Logitech M235 Wireless',
                'sku'            => 'OFC-001',
                'description'    => 'Mouse wireless 2.4GHz, baterai tahan 12 bulan, plug and play.',
                'purchase_price' => 160_000,
                'selling_price'  => 199_000,
                'stock'          => 75,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Office Supplies'],
                'name'           => 'Keyboard Logitech K120',
                'sku'            => 'OFC-002',
                'description'    => 'Keyboard kabel USB, full-size, desain tumpahan air, senyap.',
                'purchase_price' => 130_000,
                'selling_price'  => 169_000,
                'stock'          => 90,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Office Supplies'],
                'name'           => 'Webcam Logitech C270 HD',
                'sku'            => 'OFC-003',
                'description'    => 'Webcam 720p 30fps, mikrofon bawaan, plug and play USB.',
                'purchase_price' => 310_000,
                'selling_price'  => 399_000,
                'stock'          => 40,
                'minimum_stock'  => 6,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Office Supplies'],
                'name'           => 'Kertas HVS A4 80gsm 1 Rim',
                'sku'            => 'OFC-004',
                'description'    => 'Kertas fotokopi HVS A4 80 gram, 500 lembar per rim, putih cerah.',
                'purchase_price' => 42_000,
                'selling_price'  => 55_000,
                'stock'          => 180,
                'minimum_stock'  => 30,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Office Supplies'],
                'name'           => 'Monitor LG 24" Full HD IPS',
                'sku'            => 'OFC-005',
                'description'    => 'Monitor 24 inci IPS FHD 1920x1080, 75Hz, AMD FreeSync, HDMI & VGA.',
                'purchase_price' => 1_600_000,
                'selling_price'  => 1_999_000,
                'stock'          => 20,
                'minimum_stock'  => 4,
                'status'         => 'active',
            ],

            // ── Printer (5 products) ─────────────────────────────────────────
            [
                'category_id'    => $cats['Printer'],
                'name'           => 'Epson EcoTank L3250 WiFi',
                'sku'            => 'PRT-001',
                'description'    => 'Printer inkjet all-in-one WiFi, tankless, biaya cetak sangat murah.',
                'purchase_price' => 2_300_000,
                'selling_price'  => 2_799_000,
                'stock'          => 15,
                'minimum_stock'  => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Printer'],
                'name'           => 'Canon PIXMA G2020',
                'sku'            => 'PRT-002',
                'description'    => 'Printer inkjet CMYK, sistem infus, cetak & scan, tanpa WiFi.',
                'purchase_price' => 1_800_000,
                'selling_price'  => 2_199_000,
                'stock'          => 12,
                'minimum_stock'  => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Printer'],
                'name'           => 'Tinta Epson Original 003 CMYK Set',
                'sku'            => 'PRT-003',
                'description'    => 'Paket tinta original Epson 4 warna (C,M,Y,K) untuk seri L EcoTank.',
                'purchase_price' => 195_000,
                'selling_price'  => 249_000,
                'stock'          => 80,
                'minimum_stock'  => 15,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Printer'],
                'name'           => 'HP LaserJet Pro M15W WiFi',
                'sku'            => 'PRT-004',
                'description'    => 'Printer laser monokrom WiFi, cetak hingga 19 halaman/menit.',
                'purchase_price' => 1_500_000,
                'selling_price'  => 1_849_000,
                'stock'          => 8,
                'minimum_stock'  => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Printer'],
                'name'           => 'Toner HP CF217A Original',
                'sku'            => 'PRT-005',
                'description'    => 'Toner HP 17A original untuk LaserJet Pro M102/M130, yield 1600 hal.',
                'purchase_price' => 230_000,
                'selling_price'  => 299_000,
                'stock'          => 30,
                'minimum_stock'  => 5,
                'status'         => 'active',
            ],

            // ── Food & Beverage (3 products) ─────────────────────────────────
            [
                'category_id'    => $cats['Food & Beverage'],
                'name'           => 'Indomie Goreng Box isi 40',
                'sku'            => 'FNB-001',
                'description'    => 'Mie instan goreng Indomie rasa original, 1 dus isi 40 bungkus.',
                'purchase_price' => 95_000,
                'selling_price'  => 115_000,
                'stock'          => 100,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Food & Beverage'],
                'name'           => 'Aqua Galon 19 Liter',
                'sku'            => 'FNB-002',
                'description'    => 'Air mineral dalam kemasan galon AQUA isi 19 liter, segel resmi.',
                'purchase_price' => 18_000,
                'selling_price'  => 22_000,
                'stock'          => 50,
                'minimum_stock'  => 10,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['Food & Beverage'],
                'name'           => 'Kopi Kapal Api Spesial 165g',
                'sku'            => 'FNB-003',
                'description'    => 'Kopi bubuk Kapal Api spesial blend pilihan, kemasan 165 gram.',
                'purchase_price' => 15_000,
                'selling_price'  => 20_000,
                'stock'          => 80,
                'minimum_stock'  => 15,
                'status'         => 'active',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}